### PR TITLE
Update deeponet.py for tf2 multiple outputs

### PR DESCRIPTION
**Pull request by mitchelldaneker**
Sorry for making a second pull request, educated myself a bit on github and things are hopefully back on track. Thank you for the patience.

### CODE REVIEW

**Comment by vl-dud** [comment]
It's all right, I get it. But unfortunately the new branch does not contain edits that I mentioned in your previous pull request [https://github.com/vldud-off/deepxde/pull/1](https://github.com/vldud-off/deepxde/pull/1). You probably forgot to merge the changes. Check *deepxde/nn/tensorflow/__init__.py*, it contains a reference to non-existent  class `DeepONet`.

**Comment by mitchelldaneker** [comment]
> It's all right, I get it. But unfortunately the new branch does not contain edits that I mentioned in your previous pull request #1. You probably forgot to merge the changes. Check _deepxde/nn/tensorflow/**init**.py_, it contains a reference to non-existent class `DeepONet`.

DeepONet class functionality has been added for tf2, which is up to data with the DeepXDE master branch. The naming conventions should already match what you specified, and the docstrings matching yours are added for `num_outputs` and `multi_ouput_strategy`.

**Comment by vl-dud** [comment]
Is your implementation compatible with `dde.data.PDEOperatorCartesianProd`? I couldn't run *examples/operator/poisson_aligned_multioutput_pideeponet_2d.py* with Tensorflow backend.

**Comment by vl-dud** [comment]
Add new classes to __init__.py. See [https://github.com/lululxvi/deepxde/pull/1410/commits/25bf219d55b65c4d601f40456516dd1d3380f7ea](https://github.com/lululxvi/deepxde/pull/1410/commits/25bf219d55b65c4d601f40456516dd1d3380f7ea)

**Comment by mitchelldaneker** [comment]
> Is your implementation compatible with `dde.data.PDEOperatorCartesianProd`? I couldn't run _examples/operator/poisson_aligned_multioutput_pideeponet_2d.py_ with Tensorflow backend.

I see why this issue is caused. We defined the combination of the outputs differently. Yours seems to do it in the third dimension for the tensor, which makes sense. Making changes now. Can you explain why you use tf.stack in DeepONetCartesianProd vs tf.concat in DeepONet. Originally I defined mine using tf.concat, but found this was very slow in tf2.

**Comment by vl-dud** [comment]
> > Is your implementation compatible with `dde.data.PDEOperatorCartesianProd`? I couldn't run _examples/operator/poisson_aligned_multioutput_pideeponet_2d.py_ with Tensorflow backend.
> 
> I see why this issue is caused. We defined the combination of the outputs differently. Yours seems to do it in the third dimension for the tensor, which makes sense. Can you explain why you use `tf.stack` in `DeepONetCartesianProd` vs `tf.concat` in `DeepONet`. Originally I defined mine using `tf.concat`, but found this was very slow in tf2.

I had to do this because of the difference in implementation of losses in `PDEOperator` and `PDEOperatorCartesianProd`. Compare
```
def losses(self, targets, outputs, loss_fn, inputs, model, aux=None):
	f = []
	if self.pde.pde is not None:
		f = self.pde.pde(inputs[1], outputs, model.net.auxiliary_vars)
```
and
```
def _losses(self, outputs, loss_fn, inputs, model, num_func):
	bcs_start = np.cumsum([0] + self.pde.num_bcs)

	losses = []
	for i in range(num_func):
		out = outputs[i] if model.net.num_outputs > 1 else outputs[i][:, None]
		f = []
		if self.pde.pde is not None:
			f = self.pde.pde(inputs[1], out, model.net.auxiliary_vars[i][:, None])
```

**Comment by mitchelldaneker** [comment]
> > > Is your implementation compatible with `dde.data.PDEOperatorCartesianProd`? I couldn't run _examples/operator/poisson_aligned_multioutput_pideeponet_2d.py_ with Tensorflow backend.
> > 
> > 
> > I see why this issue is caused. We defined the combination of the outputs differently. Yours seems to do it in the third dimension for the tensor, which makes sense. Can you explain why you use `tf.stack` in `DeepONetCartesianProd` vs `tf.concat` in `DeepONet`. Originally I defined mine using `tf.concat`, but found this was very slow in tf2.
> 
> I had to do this because of the difference in implementation of losses in `PDEOperator` and `PDEOperatorCartesianProd`. Compare
> 
> ```
> def losses(self, targets, outputs, loss_fn, inputs, model, aux=None):
> 	f = []
> 	if self.pde.pde is not None:
> 		f = self.pde.pde(inputs[1], outputs, model.net.auxiliary_vars)
> ```
> 
> and
> 
> ```
> def _losses(self, outputs, loss_fn, inputs, model, num_func):
> 	bcs_start = np.cumsum([0] + self.pde.num_bcs)
> 
> 	losses = []
> 	for i in range(num_func):
> 		out = outputs[i] if model.net.num_outputs > 1 else outputs[i][:, None]
> 		f = []
> 		if self.pde.pde is not None:
> 			f = self.pde.pde(inputs[1], out, model.net.auxiliary_vars[i][:, None])
> ```

It should be good now. After changes to the output shape, I have uploaded a new _examples/operator/antiderivative_aligned_UQ.py_ example file fitting the new output scheme that works in both versions of tensorflow. Testing _examples/operator/poisson_aligned_multioutput_pideeponet_2d.py_ works in tf2 on my machine as well. Please give it a try.

**Comment by vl-dud** [comment]
> It should be good now. After changes to the output shape, I have uploaded a new examples/operator/antiderivative_aligned_UQ.py example file fitting the new output scheme that works in both versions of tensorflow. Testing examples/operator/poisson_aligned_multioutput_pideeponet_2d.py works in tf2 on my machine as well. Please give it a try.

Great, I think it is working correctly now.
There are still two reviews left, please answer in the appropriate threads.

**Comment by mitchelldaneker** [comment]
> Add new classes to **init**.py. See [lululxvi@25bf219](https://github.com/lululxvi/deepxde/commit/25bf219d55b65c4d601f40456516dd1d3380f7ea)

Completed

**Comment by mitchelldaneker** [comment]
> > It should be good now. After changes to the output shape, I have uploaded a new examples/operator/antiderivative_aligned_UQ.py example file fitting the new output scheme that works in both versions of tensorflow. Testing examples/operator/poisson_aligned_multioutput_pideeponet_2d.py works in tf2 on my machine as well. Please give it a try.
> 
> Great, I think it is working correctly now. There are still two reviews left, please answer in the appropriate threads.

I only see one comment you made which I did not reply to, which I just did. On my end there are no reviews in this pull request.

**Comment by vl-dud** [comment]
> I only see one comment you made which I did not reply to, which I just did. On my end there are no reviews in this pull request.

I'm talking about these reviews.

**Comment by mitchelldaneker** [comment]
> > I only see one comment you made which I did not reply to, which I just did. On my end there are no reviews in this pull request.
> 
> I'm talking about these reviews.
> 
> 

Your review is pending, I cannot see it yet. Those changes were made though.

**Pull request merged**
