### PR TITLE
Update triple.py so DeepONet can use multiple user defined losses

### PR DESCRIPTION
**Pull request by mitchelldaneker**
updated losses in triple to allow for multiple losses, and check for inputs being included in the loss function. With multiple outputs, multiple losses may be needed hence this update.

### CODE REVIEW

**Comment by vl-dud** [comment]
Could you add an example with multiple losses to the directory *examples/operator*? I would like to check before merging.

**Comment by mitchelldaneker** [comment]
[antiderivative_aligned_UQ.txt](https://github.com/vldud-off/deepxde/files/12847235/antiderivative_aligned_UQ.txt)

I'm sorry I am not familiar enough with GitHub yet to add the file to this pull request. I have uploaded it instead, please let me know if you can access it.

**Comment by vl-dud** [comment]
Just add the required files and commit to the branch of this pull request (patch-4)

**Comment by mitchelldaneker** [comment]
> Just add the required files and commit to the branch of this pull request (patch-4)

Thanks, should be added now.

**Pull request closed without merging**
